version: '3
services:
  streaming-video:
    image: streaming-video
    build:
      context: ./streaming-video
      dockerfile: Dockerfile
    container_name: streaming-video
    ports:
      - "4000:80"
    environment:
      - PORT=80
    restart: "no"
